### ISSUE TITLE
Use best_attempts to get a user's attempted drill

### ISSUE THREAD

**Issue by solderq35** [Golf-Drill-Challenge-App/Golf-App#102]
Right now all attempts of a user is fetched and then all unique drills are filtered out.
We can just check best_attempts for this instead.
Then get rid of getUnique in Utility

**Comment by solderq35** [comment]
Marked as higher priority as it has performance implications

**Comment by FrankreedX** [comment]
This would have to wait till the db is nuked and submission code would update leaderboard by itself

**Comment by solderq35** [comment]
closed as complete by pr above
