### ISSUE TITLE
View all shots pill is too plain, esp for Line test

### ISSUE THREAD

**Issue by solderq35** [Golf-Drill-Challenge-App/Golf-App#111]
Make this smaller or sth

![Image](https://github.com/Golf-Drill-Challenge-App/Golf-App/assets/41023671/409a44c2-b5f7-4670-a426-478e23bf0d0b)

**Comment by Gehrkej** [comment]
Here is the updated styling for this component.


![Image](https://github.com/Golf-Drill-Challenge-App/Golf-App/assets/91503842/0df968aa-1986-4670-8bcf-b4eeea79f9f3)


![Image](https://github.com/Golf-Drill-Challenge-App/Golf-App/assets/91503842/80da8188-c56c-41ab-ba73-52f7c7d8e544)



![Image](https://github.com/Golf-Drill-Challenge-App/Golf-App/assets/91503842/7b6fddf7-21a7-444f-b6e3-c8fa357f157a)
