### ISSUE TITLE
Description modal in Drill submission scrolls too much

### ISSUE THREAD

**Issue by FrankreedX** [Golf-Drill-Challenge-App/Golf-App#123]
It can scroll to like 5 times the content

![Image](https://github.com/Golf-Drill-Challenge-App/Golf-App/assets/41023671/c48bfc24-d6bf-4127-8a9d-908505e1d656)

**Comment by solderq35** [comment]
I think Frank said this is Android only, but if not, feel free to remove platform-issue comment

**Comment by FrankreedX** [comment]
It's both
