### ISSUE TITLE
Restart Drill button doesn't restart the drill, remove it or fix it

### ISSUE THREAD

**Issue by FrankreedX** [Golf-Drill-Challenge-App/Golf-App#124]
![Image](https://github.com/Golf-Drill-Challenge-App/Golf-App/assets/41023671/9fe0e1e2-bacd-4c2f-bf09-b21d89b8019a)

**Comment by solderq35** [comment]
Marked as medium priority due to broken functionality when clicking button as opposed to just styling issues. Maybe need more discussion as a team on if we need this button.

**Comment by solderq35** [comment]
Assigned Jake for now as I think he worked the most on the drill submissions

**Comment by Gehrkej** [comment]
I have gotten this to work, it is apart of PR #136
