### ISSUE TITLE
Change the Leave Drill modal's color

### ISSUE THREAD

**Issue by FrankreedX** [Golf-Drill-Challenge-App/Golf-App#126]
This color doesn't match the rest of our app

![Image](https://github.com/Golf-Drill-Challenge-App/Golf-App/assets/41023671/9fc8d93a-29cd-4061-8e6e-6b96993280a0)

**Comment by Gehrkej** [comment]
address in #94 


![Image](https://github.com/Golf-Drill-Challenge-App/Golf-App/assets/91503842/25b41808-0faf-48c2-b863-ec638a8b3847)
