### ISSUE TITLE
Remove user's ability to update email in the User Profile Settings modal

### ISSUE THREAD

**Issue by artkolpakov** [Golf-Drill-Challenge-App/Golf-App#132]
Following feedback from the coach, it has been determined that users should not have the capability to update their email addresses at any point. Therefore, the option to update the email field in the profile settings modal needs to be removed:

![Image](https://github.com/Golf-Drill-Challenge-App/Golf-App/assets/91341345/65a91d19-ba77-4dc2-8f14-8ffb1dadfd0e)

**Comment by solderq35** [comment]
Closed by https://github.com/Golf-Drill-Challenge-App/Golf-App/pull/139
