### ISSUE TITLE
When a drill is clicked in the assignment screen, the drillList can't be accessed anymore

### ISSUE THREAD

**Issue by FrankreedX** [Golf-Drill-Challenge-App/Golf-App#143]
When a drill is clicked in the assignment screen, the Drill tab is opened with that drill. The return button will return to the assignment screen instead of the drillList screen, making the drillList screen not accessible anymore. Even pressing the "Drill" button on the nav bar won't work

https://github.com/Golf-Drill-Challenge-App/Golf-App/assets/41023671/21cfd0a4-9515-4b26-aaae-2835f85be8bc

**Comment by solderq35** [comment]
issue seems fixed by pr above
