### ISSUE TITLE
[Mostly Done] Change Date Time function to be milliseconds

### ISSUE THREAD

**Issue by Gehrkej** [Golf-Drill-Challenge-App/Golf-App#144]
### Issue Description
Currently, the `formatDate` function in `Utility.js` isn't using milliseconds. The timestamp in the `uploadData` in `input.js` is using milliseconds so we need to adjust this to be consistent throughout. Per Franks we will be using milliseconds

**Comment by solderq35** [comment]
- [x] Completed this for drill submission (https://github.com/Golf-Drill-Challenge-App/Golf-App/pull/86)
- [ ] Potentially refactor this in Utility.js's formatDate function / in Plan page

**Comment by solderq35** [comment]
Completed task 2 in latest commit of my PR

**Comment by solderq35** [comment]
Closed by https://github.com/Golf-Drill-Challenge-App/Golf-App/pull/86
