### ISSUE TITLE
Adjust Color on TextInput within drillInput component

### ISSUE THREAD

**Issue by Gehrkej** [Golf-Drill-Challenge-App/Golf-App#146]
### Issue description
Currently the outline of the textInput outline and cursor is purple within the drillInput component. We should adjust this to be the same orange we have used for the other components.

Current:
<img width="114" alt="Screenshot 2024-04-12 at 12 02 25 PM" src="https://github.com/Golf-Drill-Challenge-App/Golf-App/assets/91503842/c379c455-3671-4fec-84a3-2650536e8ca6">

**Comment by FrankreedX** [comment]
Orange is a bit strong...

![Image](https://github.com/Golf-Drill-Challenge-App/Golf-App/assets/41023671/04376b08-c638-4243-bd07-40808971f7bb)
