### ISSUE TITLE
Check Update Leaderboard Logic

### ISSUE THREAD

**Issue by solderq35** [Golf-Drill-Challenge-App/Golf-App#150]
When no one is on the leaderboard yet for a drill, the leaderboard updates as expected. When there is already someone else on the leaderboard, submitting a drill does not always update the leaderboard as expected. Check how updateLeaderboard hook is called

**Comment by FrankreedX** [comment]
When a drill is submitted, no leaderboard update is currently being triggered

**Comment by solderq35** [comment]
Issues
- some "lower is better" sorting is inconsistent (e.g. strokes gained ordered by lowest on top)
- check whether the case of "I already have a score on the board and I just got a better score" updates the leaderboard correctly (seems not to)
- Move triggering the leaderboard update to happen on submit drill submission button press (input.js file)

**Comment by solderq35** [comment]
Did some preliminary work on a branch (https://github.com/Golf-Drill-Challenge-App/Golf-App/pull/159), but after discussing with Jake we might move to a new PR (trying to trigger leaderboard update on drill submit) and just keep this for reference.

**Comment by Gehrkej** [comment]
I got the the functionality of updating upon a better score being submitted as well as when a user does not have an attempt for a given drill. A couple concerns around the "best_attempts" structure came up when implementing this. Please see #161 for more information and the implementation of this.
