### ISSUE TITLE
Leaderboard data doesn't have units

### ISSUE THREAD

**Issue by FrankreedX** [Golf-Drill-Challenge-App/Golf-App#168]
Currently, the leaderboard always displays "ft" for units.

![Image](https://github.com/Golf-Drill-Challenge-App/Golf-App/assets/41023671/03741ba4-3be6-4d4b-8171-66d1b16a7b08)

Maybe add "distanceMeasure" to aggOutputs?

![Image](https://github.com/Golf-Drill-Challenge-App/Golf-App/assets/41023671/1f03e0eb-92d8-43fc-87dc-7473633afcd1)

**Comment by solderq35** [comment]
I assume this is fixed by above PR
