### ISSUE TITLE
Owner and Coach should be able to Archive users, Kick and Blacklist users, and any other user management actions

### ISSUE THREAD

**Issue by FrankreedX** [Golf-Drill-Challenge-App/Golf-App#180]

**Comment by Gehrkej** [comment]
Remove/Kick feature has been started on #190

**Comment by Gehrkej** [comment]
Remove/Kick feature is functional. One thing to note is this user stays within the auth section of fire store. This is a good thing as we move towards having the application for multiple teams but it might cause some issues if a player is removed then logs in again as I believe the "sign up" functionality is what populates the user in the teams "users" table currently.
