### ISSUE TITLE
Owner and Coach should be able to see all assigned drills, and manage (delete) assignments

### ISSUE THREAD

**Issue by FrankreedX** [Golf-Drill-Challenge-App/Golf-App#182]
They also should be able to click on a completed assignment and be led to that attempt

**Comment by solderq35** [comment]
Related sub-task: https://github.com/Golf-Drill-Challenge-App/Golf-App/issues/197

**Comment by solderq35** [comment]
I think https://github.com/Golf-Drill-Challenge-App/Golf-App/pull/208 might address this, but let's double check with Andy

**Comment by solderq35** [comment]
Coach feedback: See a list of player pfp or initials per assignment, click on specific assignment to see details like player full names
