### ISSUE TITLE
Leaderboard wipe for every year 

### ISSUE THREAD

**Issue by hannacol** [Golf-Drill-Challenge-App/Golf-App#189]
Removing the leaderboard data from database after the end of every season

**Comment by Gehrkej** [comment]
One Idea I had for this was we could provide a "Start new season" button/function for the coach to click on the UI that could take him through all the steps to start a new season and it would give us the exact date to look for when filtering the attempts for the leaderboard. Just a thought.

**Comment by solderq35** [comment]
Maybe send an email to the coach asking if he prefers:
- button
- automate reset per year somehow

**Comment by hannacol** [comment]
> Maybe send an email to the coach asking if he prefers:
> 
> * button
> * automate reset per year somehow

Let's do button

**Comment by hannacol** [comment]
Add a menu button on team page with the following:

- Team Settings
- Wipe Season

Team settings as it's own issue

**Comment by solderq35** [comment]
Coach's comment: 

Manual button press is ok. 

Maybe also add a prompt to let the coach know, but coach needs to confirm button  press manually.

Leaderboard Wipe at ~September 1st
