### ISSUE TITLE
Assigned Drill Error upon new account creation

### ISSUE THREAD

**Issue by Gehrkej** [Golf-Drill-Challenge-App/Golf-App#191]
### Description
When a new account is created, there seems to be an error with the query to get the assigned drills. 
### Steps to reproduce
- log out and get to the sign up page
- Create a new account
- upon hitting the submit button, you should see the error screen. 

### Screenshot:
![image](https://github.com/Golf-Drill-Challenge-App/Golf-App/assets/91503842/30e27747-bad4-4cc6-9b4a-41c6c210c9d0)

**Comment by Gehrkej** [comment]
upon the first refresh this resolves and goes to normal "no drills assigned". It is just on the initial sign up.

**Comment by Gehrkej** [comment]
Just made another account and it didn't happen so I wonder if it is just if firebase has time to update before the assignment screen makes the query...

**Comment by solderq35** [comment]
I assume this is fixed by above PR
