### ISSUE TITLE
Figma - Drill Details Screen

### ISSUE THREAD

**Issue by artkolpakov** [Golf-Drill-Challenge-App/Golf-App#2]
### Task Description:
Create a Figma design prototype for the drill details screen of our application.

### Steps to Reproduce:
1. Access the Figma [file](https://www.figma.com/file/8fP7vgmQ9kNhYeyFIS5guP/OSU-Golf-App-Prototype?type=design&node-id=4%3A11&mode=design&t=2173H6Zz7oQ4bgam-1).
2. Develop a visual representation of the drill details screen.
3. Ensure the design aligns with the app's overall theme and user experience.

### Additional Information:
- This prototype will be used for reference and implementation in the app.
- Please follow the design guidelines provided in our documentation.

**Comment by Gehrkej** [comment]
Created a mock up with a video and text description as well as a start drill button.

**Comment by Gehrkej** [comment]
Integrated this mock up with franks flow
