### ISSUE TITLE
Drill Submit shotNum not defined

### ISSUE THREAD

**Issue by solderq35** [Golf-Drill-Challenge-App/Golf-App#217]
Triggered on drill submit button press.

```
 ERROR  TypeError: Cannot read property 'shotNum' of undefined

This error is located at:
    in Input (created by Index)
```    

![image](https://github.com/Golf-Drill-Challenge-App/Golf-App/assets/82061589/8f32c493-fdae-4731-8dfe-aaf5980ff624)

**Comment by Gehrkej** [comment]
could you show me how to reproduce this in our meeting tomorrow?

**Comment by solderq35** [comment]
This should already be fixed in layout branch, by the PR linked above.

However, the bug could be triggered (on old app version) whenever you pressed the "start drill" / "restart drill" button (sorry, "drill submit button" wasn't very clear).
