### ISSUE TITLE
iOS keyboard (numbers) doesn't have negative sign

### ISSUE THREAD

**Issue by solderq35** [Golf-Drill-Challenge-App/Golf-App#228]
![image](https://github.com/Golf-Drill-Challenge-App/Golf-App/assets/82061589/a2adfe21-de9a-4c8a-9dec-c6a47cc9823c)

**Comment by Gehrkej** [comment]
I started looking more into this and seems like we might just have to use the "numbers-and-punctuation" on IOS but can keep the numeric for Andriod.. This would be in the drillInput component.
