### ISSUE TITLE
"Cannot read property 'name' of undefined" error when signing out

### ISSUE THREAD

**Issue by FrankreedX** [Golf-Drill-Challenge-App/Golf-App#305]
![Screenshot 2024-08-07 at 8 28 29 AM](https://github.com/user-attachments/assets/bdad35a1-d2f6-496b-9e8b-aa6d44574db7)

**Comment by solderq35** [comment]
Should be fixed by https://github.com/Golf-Drill-Challenge-App/Golf-App/issues/288
