### ISSUE TITLE
Layout and Navigation Implementation - Drill Submission / Shot

### ISSUE THREAD

**Issue by FrankreedX** [Golf-Drill-Challenge-App/Golf-App#36]
Implement the bare skeleton code to layout components and navigation for the Drill Details - Shot screen. This screen should be implemented in a way where an object can be passed in and the drill page is dynamically generated.
Link to the screen in question: 

- [x] Cancel button (goes back to Drill Details - Description)
- [x] Title (20 Shot Challenge and Shot number)
- [x] Details Overlay button. Display Drill Submission - Details Overlay modal when clicked.
- [x] Core data requirements (Target Distance and others). This must be implemented in a way where a list of attributes can be passed in and properly displayed.
- [x] Data inputs (Carry Distance, etc.). This must be implemented in a way where a list of attributes can be passed in and properly displayed.
- [x] Back to Latest / Next Shot button. If current shot is not "current", then display the "Back to Latest" button, otherwise display "Next Shot" button
- [x] View all Shots button. Display the Drill Submission - Shot Navigation modal when clicked.

![Image](https://github.com/Golf-Drill-Challenge-App/Golf-App/assets/41023671/2d805d8c-8170-48a8-abbe-db7bbecd924c)

**Comment by Gehrkej** [comment]
I will start on this one since I have a base already made in my test of react native paper

**Comment by Gehrkej** [comment]
The progress can be found [here](https://github.com/Golf-Drill-Challenge-App/Golf-App-Test/tree/paper-test)

**Comment by solderq35** [comment]
For the "Core Data" subtask, for Firebase integration this documentation should help: https://firebase.google.com/docs/firestore/query-data/get-data

To initialize the database you can refer to my firebase.config.js in my login test branch: https://github.com/Golf-Drill-Challenge-App/Golf-App/tree/solderq35/login-revamp-test

Frank also started work with some mock (harcoded json) data here for displaying drills: https://github.com/Golf-Drill-Challenge-App/Golf-App-Test/commits/frankreed/mock-drills/

**Comment by Gehrkej** [comment]
For the task " Cancel button (goes back to Drill Details - Description)" it is currently a left cheveron and not the "cancel" text
