### ISSUE TITLE
Layout and Navigation Implementation - Team

### ISSUE THREAD

**Issue by artkolpakov** [Golf-Drill-Challenge-App/Golf-App#58]
Implement the “Team” screen to match the [Figma design](https://www.figma.com/file/8fP7vgmQ9kNhYeyFIS5guP/OSU-Golf-App-Prototype?type=design&node-id=1452-904&mode=design&t=oXpSKOSwHQB3SPoi-0).

<img src="https://github.com/Golf-Drill-Challenge-App/Golf-App/assets/91341345/7def5628-6cdb-4f4b-80f6-0574a4c4362c" width=30% height=30%>

Acceptance criteria:
- [x] Header with title and back button 
- [x] Image
- [x] Title 
- [x] Search bar
- [x] Scrollview mapping people.json mock file data
- [x] Navbar

Potential TODO as of Jan 15, 2024, after https://github.com/Golf-Drill-Challenge-App/Golf-App/commit/f9d7258ef1438aa413ee04a592f8d3b6f52d172c
- [ ] Style settings popup more maybe
- [ ] Style user profile and stats pages

**Comment by solderq35** [comment]
https://github.com/Golf-Drill-Challenge-App/Golf-App/pull/59

**Comment by solderq35** [comment]
- [ ] Add statistic pages for team data, reference https://github.com/Golf-Drill-Challenge-App/Golf-App/pull/57
- [ ] Change settings popup from a modal to bottomsheet (chose the wrong react native paper component last time)
- [ ] I need to add a back button to header (will reference the code from drill description I guess)
- [ ] Need to double check coloring, e.g. on the settings icon

**Comment by hannacol** [comment]
Fully styled
