### ISSUE TITLE
Drill Submission Page: View flexbox +  bottom padding issue

### ISSUE THREAD

**Issue by solderq35** [Golf-Drill-Challenge-App/Golf-App#70]
## Issue
**EDIT**
Affected Pages (View component + flex style):
- [ ] Drill Submission Input Page
  - ![image](https://github.com/Golf-Drill-Challenge-App/Golf-App/assets/82061589/defc7778-a7bd-42c9-93b9-3ca4ec7846f0)
  - After https://github.com/Golf-Drill-Challenge-App/Golf-App/pull/67 is merged, the only page this still seems to be an issue for is drill submission
    -  For Drill Submission Input, the issue seems to come from `GestureHandlerRootView style={{ flex: 1 }}`
  - However, it could affect any other page with a `View` type of component (including `SafeAreaView`) and `style:{{flex: 1}}` (or similar)
  
## Solutions
- Add `edges` argument to view component, leave out `bottom`: https://github.com/Golf-Drill-Challenge-App/Golf-App/pull/67
```js
      <SafeAreaView
        // flex: without this the scrollview automatically scrolls back up when finger no longer held down
        style={{ flex: 1 }}
        // edges: to remove bottom padding above tabbar. Maybe move this (and PaperProvider) into app/_layout.js?
        edges={["right", "top", "left"]}
      >
```
- Can expand this fix to other screens (maybe on another PR), and refactor the SafeArea and PaperProvider into `app/_layout.js` or something (to avoid redundancy on calling these on every screen)

**Comment by FrankreedX** [comment]
I think this issue has been addressed
